LQNL\ServidorBundle\Entity\Disponibilidade:
    type: entity
    table: disponibilidade
    indexes:
        fk_disponibilidade_responsavel:
            columns:
                - responsavel
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dia:
            type: date
            nullable: false
            comment: ''
        turno:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
    manyToOne:
        responsavel:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                responsavel:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
