LQNL\ServidorBundle\Entity\Recolhimento:
    type: entity
    table: recolhimento
    id:
        id:
            type: bigint
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        data:
            type: datetime
            nullable: false
            comment: ''
        papel:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        metal:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        eletronico:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        vidro:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        plastico:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        outros:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        total:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
    lifecycleCallbacks: {  }
