servidor:
    resource: "@ServidorBundle/Resources/config/routing.yml"
    prefix:   /admin

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /

autenticacao:
    resource: "@AutenticacaoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
