security:
    encoders:
        LQNL\AutenticacaoBundle\Entity\Usuario:
            algorithm: sha512
            encode_as_base64: false
            iterations: 7
        LQNL\ServidorBundle\Entity\Usuario:
            algorithm: sha512
            encode_as_base64: false
            iterations: 7

    role_hierarchy:
        ROLE_USER:       IS_AUTHENTICATED_ANONYMOUSLY
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]
    
    providers:
        usuario_db:
            id: usuario_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        secured_area:
            pattern:    ^/
            anonymous: ~
            
            form_login:
                login_path:  /
                check_path:  /login_check
                default_target_path: /home
                always_use_default_target_path: false
                use_referer: true
            logout:
                path:  /logout
#            http_basic:
#                realm: "Secured Demo Area"

    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/novoUsuario, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperarSenha, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperandoSenha, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/edit, roles: ROLE_USER }
        - { path: ^/show, roles: ROLE_USER }
        - { path: ^/solicitacao, roles: ROLE_USER }
#        - { path: ^/usuarios, roles: ROLE_USER }
