security:
    encoders:
        LQNL\AutenticacaoBundle\Entity\Usuario:
            algorithm: sha512
            encode_as_base64: false
            iterations: 7

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        usuario_db:
            id: usuario_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            
            form_login:
                login_path:  /
                check_path:  /login_check
                default_target_path: /home
                always_use_default_target_path: true
                use_referer: false
            logout:
                path:  /logout
            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"

    access_control:
        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/novoUsuario, roles: IS_AUTHENTICATED_ANONYMOUSLY }
